spring:
  datasource:
    url: jdbc:mysql://10.8.229.94:63751/wsnews?&useSSL=false&characterEncoding=utf-8&serverTimezone=CTT
    username: appTeam2
    password: bZ^0!qyOu9&WJ*qO
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8081
mybatis:
  type-aliases-package: com.crow.entity

pythonroute:
  python-package-root: /usr/wsnews/py/
#  python-package-root: D:/myProject/wsnewsappgroup2/wsnews-java/src/main/java/com/crow/pythonscrips/
