spring:
  datasource:
    url: jdbc:mysql://10.8.229.94:63751/wsnews?&useSSL=false&characterEncoding=utf-8&serverTimezone=CTT

    username: appTeam2
    password: bZ^0!qyOu9&WJ*qO
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://10.8.229.94:63751/wsnews?&useSSL=false&characterEncoding=utf-8&serverTimezone=CTT
#    url: jdbc:mysql://127.0.0.1:3306/wsnews?&useSSL=false&characterEncoding=utf-8&serverTimezone=CTT
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  type-aliases-package: com.crow.entity